### ISSUE TITLE
Consider changing the lifetime of the of the output

### ISSUE THREAD

**Issue by tbu-** [fastfailures/e164-phones-countries#1]
Currently, the lifetime of the output is implicitely as long as the input's lifetime:

```
fn find_iso_3166<'a>(phone: &'a str) -> &'a str;
```

But actually, your output strings live much longer, they have the `'static` lifetime, so the following declaration might be more fitting:

```
fn find_iso_3166(phone: &str) -> &'static str;
```

**Comment by visualjeff** [comment]
Really appreciate the comment.  Makes sense.

**Comment by tbu-** [comment]
This was fixed by https://github.com/visualjeff/e164-phones-countries/commit/10a8aea05dc3e3ec931ac0dfa4deeae38d3af2ff.
